name: Tarpaulin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin
    - name: Build
      run: cargo build --features="glam" --verbose
    - name: Run tests
      run: cargo test --features="glam" --verbose
    - name: Generate Code Coverage Report
      run: |
        cargo tarpaulin --features="glam" --out Html
        mv tarpaulin-report-html $GITHUB_WORKSPACE/coverage
    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: $GITHUB_WORKSPACE/coverage
